name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

inputs:
  ticketPrefix:
    description: 'Jira Ticket Prefix'
    required: true
    default: 'ABC'
  prTitle:
    description: 'PR title'
    required: true

# Define your outputs here.
outputs:
  ticketValidationStatus:
    description: 'wheter ticket validation succeded'

runs:
  using: node20
  main: dist/index.js
